weapon_mapping = {
    "Sploosh-o-matic": "vsploosh.png",
    "Splattershot Jr.": "jr.png",
    "Splash-o-matic": "vsplash.png",
    "Custom Splattershot Jr.": "cjr.png",
    "Neo Sploosh-o-matic": "neosploosh.png",
    "Neo Splash-o-matic": "neosplash.png",
    "Aerospray MG": "aeroMG.png",
    "Aerospray RG": "aeroRG.png",
    "Splattershot": "vshot.png",
    ".52 Gal": "52.png",
    "N-ZAP '85": "zap85.png",
    "Splattershot Pro": "vpro.png",
    ".96 Gal": "v96.png",
    "Jet Squelcher": "vjet.png",
    "Splattershot Nova": "vnova.png",
    "Luna Blaster": "luna.png",
    "Blaster": "vblast.png",
    "Range Blaster": "range.png",
    "Clash Blaster": "vclash.png",
    "Rapid Blaster": "vrapid.png",
    "Rapid Blaster Pro": "vrapidpro.png",
    "S-BLAST '92": "sblast92.png",
    "L-3 Nozzlenose": "vl3.png",
    "H-3 Nozzlenose": "vh3.png",
    "Squeezer": "vsqueez.png",
    "Carbon Roller": "vcarbon.png",
    "Splat Roller": "vroller.png",
    "Dynamo Roller": "vdyna.png",
    "Flingza Roller": "vflingza.png",
    "Big Swig Roller": "bigswig.png",
    "Inkbrush": "vinkbrush.png",
    "Octobrush": "voctobrush.png",
    "Painbrush": "vpain.png",
    "Classic Squiffer": "vsquidd.png",
    "Splat Charger": "vcharger.png",
    "Splatterscope": "vchargescoped.png",
    "E-liter 4K": "eliter.png",
    "E-liter 4K Scope": "literscoped.png",
    "Bamboozler 14 Mk I": "vbamboo.png",
    "Goo Tuber": "vgoo.png",
    "Snipewriter 5H": "pencil.png",
    "Slosher": "vslosh.png",
    "Tri-Slosher": "vtri.png",
    "Sloshing Machine": "vmach.png",
    "Bloblobber": "blob.png",
    "Explosher": "vexplo.png",
    "Dread Wringer": "dread.png",
    "Mini Splatling": "vmini.png",
    "Heavy Splatling": "vheavy.png",
    "Hydra Splatling": "vhydra.png",
    "Ballpoint Splatling": "vbp.png",
    "Nautilus 47": "vnaut.png",
    "Heavy Edit Splatling": "vedit.png",
    "Dapple Dualies": "vdapple.png",
    "Splat Dualies": "vdualie.png",
    "Glooga Dualies": "vglooga.png",
    "Dualie Squelchers": "vds.png",
    "Dark Tetra Dualies": "darktetra.png",
    "Douser Dualies FF": "vdouser.png",
    "Splat Brella": "vbrella.png",
    "Tenta Brella": "vtent.png",
    "Undercover Brella": "vunder.png",
    "Recycled Brella 24 Mk I": "recycbrella.png",
    "Tri-Stringer": "vbow.png",
    "REEF-LUX 450": "reeflux.png",
    "Splatana Stamper": "vstamp.png",
    "Splatana Wiper": "vwiper.png",
}